[package]
name = "vlazed/rink"
version = "0.1.0"
license = "MIT"
exclude = ["scripts"]
include = ["default.project.json"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Import = "vocksel/import@2.1.0"


[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"